version: '3.1'

services: 
  mariadb:
    build: ./dockerfiles/mariadb/
    volumes:
      - ./dockerfiles/mariadb/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: comicManager
      MYSQL_USER: admin
      MYSQL_PASSWORD: mariadb
      MYSQL_ROOT_PASSWORD: mariadb
  express:
    build: ./dockerfiles/express/
    volumes:
      - ./dockerfiles/express/src:/server
    ports:
      - 3334:3334
    links:
      - mariadb
    command: [sh, -c, npm install && npm start]
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - 3335:8080
    volumes:
      - ../dockerfiles/swagger/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
    links:
      - express
  react:
    build: ./dockerfiles/react/
    ports:
      - 3336:80
    links:
      - express
