version: '3.1'

services: 
  mariadb:
    build: ./dockerfiles/mariadb/
    volumes:
      - ./dockerfiles/mariadb/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: comicManager
      MYSQL_USER: admin
      MYSQL_PASSWORD: mariadb
      MYSQL_ROOT_PASSWORD: mariadb
    ports:
      - 3306:3306
