version: '3.1'

services: 
  mariadb:
    build: ./dockerfiles/mariadb/
    volumes:
      - ./dockerfiles/mariadb/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: comicManager
      MYSQL_USER: admin
      MYSQL_PASSWORD: mariadb
      MYSQL_ROOT_PASSWORD: mariadb
  express:
    build: ./dockerfiles/express/
    volumes:
      - ./dockerfiles/express/src:/server
    ports:
      - 3334:3334
    links:
      - mariadb
    command: [sh, -c, npm install && npm start]
  react:
    build: ./dockerfiles/react/
    volumes:
      - ./dockerfiles/react/:/app
    ports:
      - 3335:3000
    links:
      - express