version: '3.1'

services: 
  mariadb:
    build: ./dockerfiles/mariadb/
    volumes:
      - ./dockerfiles/mariadb/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: comicManager
      MYSQL_USER: admin
      MYSQL_PASSWORD: mariadb
      MYSQL_ROOT_PASSWORD: mariadb
  express:
    build: ./dockerfiles/express/
    volumes:
      - ./dockerfiles/express/src:/server
    ports:
      - 3334:3334
    links:
      - mariadb
    command: [sh, -c, npm install && npm start]
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 3335:8080
    volumes:
      - ./dockerfiles/swagger/openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      API_URL: /openapi.yaml
