version: '3.1'

services: 
  mariadb:
    image: hirarira/comicmanager-mariadb:latest
    volumes:
      - ./dockerfiles/mariadb/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: comicManager
      MYSQL_USER: admin
      MYSQL_PASSWORD: mariadb
      MYSQL_ROOT_PASSWORD: mariadb
  express:
    image: hirarira/comicmanager-express:latest
    volumes:
      - ./dockerfiles/express/src:/server
    links:
      - mariadb
    command: [sh, -c, npm install && npm start]
  nginx:
    image: hirarira/comicmanager-nginx:latest
    volumes:
      - react-build:/usr/share/nginx/html/
    links:
      - express
    ports:
      - 8001:80
volumes:
  react-build: