swagger: "2.0"
info:
  description: "Use ComicManager.<br>https://github.com/hirarira/comicManager"
  version: "0.7.0"
  title: "comicManager Express API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3334"
schemes:
- "http"
paths:
  /status:
    get:
      summary: "ステータスチェック"
      description: "APIが起動しているかのステータスを返します"
      tags:
        - "status"
      responses:
        "200":
          description: "成功時"
          schema:
            $ref: "#/definitions/ResponseStandard"
  /get/user/{userid}:
    get:
      summary: "ユーザ情報取得"
      description: "ユーザの情報を返します"
      tags:
        - "get"
      parameters:
      - name: "userid"
        in: "path"
        description: "取得したいUserのID"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "成功時"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "ok"
              message:
                type: "string"
                example: ""
              body:
                type: "object"
                properties:
                  id:
                    type: "integer"
                    example: "1"
                  username:
                    type: "string"
                    example: "test"
                  pass:
                    type: "string"
                    example: "hoge"
  /get/authors:
    get:
      summary: "著者一覧取得"
      description: "著者情報の一覧を返します"
      tags:
        - "get"
      responses:
        "200":
          description: "成功時"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "ok"
              message:
                type: "string"
                example: ""
              body:
                type: "array"
                items:
                  $ref: "#/definitions/ComicAuthor"
  /get/comic/{comicID}:
    get:
      summary: "コミック情報取得"
      description: "コミックの情報を返します"
      tags:
        - "get"
      parameters:
      - name: "comicID"
        in: "path"
        description: "取得したいコミックのID"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "成功時"
          schema:
            type: "object"
            properties:
              status: 
                type: "string"
              message: 
                type: "string"
              body: 
                required: 
                  - "about"
                  - "author"
                  - "review"
                  - "detail"
                properties: 
                  about:
                    $ref: "#/definitions/ComicAbout"
                  author: 
                    $ref: "#/definitions/ComicAuthor"
                  review: 
                    $ref: "#/definitions/ComicReview"
                  detail: 
                    type: "array"
                    items:
                      $ref: "#/definitions/ComicVol"
  /get/comicList:
    get:
      summary: "コミック一覧情報取得"
      description: "コミックの一覧を返します"
      tags:
        - "get"
      responses:
        "200":
          description: "成功時"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ComicAbout"
  /create/author:
    post:
      summary: "著者を作成する"
      description: "著者を作成する"
      tags:
        - "create"
      consumes:
        - application/json
      parameters:
      - in: "body"
        name: "author"
        schema:
          type: "object"
          required:
            - authorName
          properties:
            name:
              description: "著者の名前"
              type: "string"
      responses:
        "200":
          description: "成功時"
          schema:
            $ref: "#/definitions/ResponseStandard"
        "400":
          description: "失敗時"
          schema:
            $ref: "#/definitions/ResponseStandard"
definitions:
  ResponseStandard:
    type: "object"
    properties:
      status:
        type: "string"
        example: "ok"
      message:
        type: "string"
        example: "status ok"
      body:
        type: "string"
        example: ""
  ComicReview:
    type: "object"
    required: 
      - "id"
      - "comicID"
      - "userID"
      - "rate"
      - "comment"
    properties: 
      id: 
        type: "number"
      comicID: 
        type: "number"
      userID: 
        type: "number"
      rate: 
        type: "number"
      comment: 
        type: "string"
  ComicAbout:
      type: "object"
      required: 
        - "id"
        - "title"
        - "authorID"
        - "endFlag"
        - "image"
      properties: 
        id: 
          type: "number"
        title: 
          type: "string"
        authorID: 
          type: "number"
        endFlag: 
          type: "boolean"
  ComicAuthor:
    type: "object"
    required: 
      - "id"
      - "name"
    properties: 
      id: 
        type: "number"
      name: 
        type: "string"
  ComicVol:
    type: "object"
    properties:
      id: 
        type: "number"
      comicID: 
        type: "number"
      number: 
        type: "string"
      image: 
        type: "string"
      info: 
        required: 
          - "id"
          - "comicVolID"
          - "userID"
          - "readFlag"
          - "readDate"
          - "buyFlag"
          - "buyDate"
          - "comment"
        properties: 
          id: 
            type: "number"
          comicVolID: 
            type: "number"
          userID: 
            type: "number"
          readFlag: 
            type: "boolean"
          readDate: 
            type: "number"
          buyFlag: 
            type: "boolean"
          buyDate: 
            type: "number"
          comment: 
            type: "string"
        type: "object"
