swagger: "2.0"
info:
  description: "Use ComicManager.<br>https://github.com/hirarira/comicManager"
  version: "1.0.0"
  title: "comicManager Express API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3334"
schemes:
- "http"
paths:
  /status:
    get:
      summary: "ステータスチェック"
      description: "APIが起動しているかのステータスを返します"
      tags:
        - "status"
      responses:
        "200":
          description: "成功時"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "ok"
              message:
                type: "string"
                example: "status ok"
              body:
                type: "string"
                example: ""
  /get/user/{userid}:
    get:
      summary: "ユーザ情報取得"
      description: "ユーザの情報を返します"
      tags:
        - "get"
      parameters:
      - name: "userid"
        in: "path"
        description: "取得したいUserのID"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "成功時"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "ok"
              message:
                type: "string"
                example: ""
              body:
                type: "object"
                properties:
                  id:
                    type: "integer"
                    example: "1"
                  username:
                    type: "string"
                    example: "test"
                  pass:
                    type: "string"
                    example: "hoge"
  /get/authors:
    get:
      summary: "著者一覧取得"
      description: "著者情報の一覧を返します"
      tags:
        - "get"
      responses:
        "200":
          description: "成功時"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "ok"
              message:
                type: "string"
                example: ""
              body:
                type: "array"
                items:
                  type: "object"
                  properties:
                    id:
                      type: "integer"
                      example: "1"
                    name:
                      type: "string"
                      example: "test"
                  

